export const SYSTEM_LOCATION_PRIMARY = 0;
export const SYSTEM_LOCATION_FRONT = 1;
export const SYSTEM_LOCATION_AFT = 2;
export const SYSTEM_LOCATION_PORT_FRONT = 31;
export const SYSTEM_LOCATION_PORT_AFT = 32;
export const SYSTEM_LOCATION_STARBOARD_FRONT = 41;
export const SYSTEM_LOCATION_STARBOARD_AFT = 42;
