version: '3.7'

services:
  mariadb:
    build:
      context: docker/mariadb
    volumes:
      - .:/usr/src/fieryvoid
    ports:
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fieryvoid